# Generated by Django 5.2.5 on 2025-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('BR', 'BORRADOR'), ('PU', 'PUBLICADO'), ('PR', 'PRIVADO')], default='BR', max_length=50)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('seller', models.CharField(blank=True, max_length=120, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('product_dimensions', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
