# Generated by Django 5.2.5 on 2025-09-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PU', 'PUBLICADO'), ('BR', 'BORRADOR'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
    ]
