# Generated by Django 5.2.5 on 2025-09-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_productmodel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='state',
        ),
    ]
